export const ACTION_TYPES = {
  SET_FILTER: 'SET_FILTER',
  ADD_TODO: 'ADD_TODO',
  EDIT_TODO: 'EDIT_TODO',
  DELETE_TODO: 'DELETE_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  DONE_ALL_TODO: 'DONE_ALL_TODO',
  CLEAR_DONE_TODO: 'CLEAR_DONE_TODO',
}